name: Programming Books I've Read

permissions:
  contents: write

concurrency:
  group: goodreads-update
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-goodreads-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Goodreads profile
        uses: lancefrench/goodreads-profile-workflow@c23d5d95bc54f7b983c6d879e1134d61429edbc7
        with:
          goodreads_user_id: ${{ secrets.GOODREADS_USER_ID }}
          shelf: programming

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Goodreads books"
