name: My Favorite Books I've Read

on:
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-goodreads-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Goodreads Profile Workflow
        uses: zwacky/goodreads-profile-workflow@main

        with:
          goodreads_user_id: "121646211"
          shelf: "read"
          max_books_count: 5
          readme_file_path: "./README.md"
          output_only: false
          comment_tag_name: "GOODREADS-LIST"
          template: "- [$title]($url) by $author ($my_rating_stars)"
          sort_by_fields: ">my_rating_stars"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated Goodreads books" || exit 0
          git push
